### ISSUE TITLE
(Enhancement) Return to Start Menu on Crash

### ISSUE THREAD

**Issue by AbsorbingSafe11** [alcatrazEscapee/Chocolate#1]
Since Vanilla Fix won't be receiving a Minecraft Forge 1.16.3 update in the foreseeable future, can you please add the ability for crashes to return to menu, instead of closing the game?

This is especially helpful to people like me who play large modpacks with 15 minute start-up times, as well as people (also like me) who are unlucky and discover every possible block combination that causes crashes.

**Comment by alcatrazEscapee** [comment]
This doesn't *really* fit into the criteria I would like for what I'd want to include into this mod, as I'd rather keep it fairly targeted towards world generation (as that's my area of expertise)

> I am open to fixing other potential issues in this mod. However, due to my own area of expertise, and plan for this mod, requirements for possible future vanilla and/or forge bugfixes are:
> 
> - It needs to be deterministically fixable, without breaking vanilla contracts or causing undue pain to other mods which may rely on some vanilla behavior.
> - It should be a high visibility or high impact bug that predominantly affects modded or data pack world generation.

That said, if this is a highly requested feature I may look into it.

**Comment by AbsorbingSafe11** [comment]
I wasn't sure on the difficulty of coding and, it seemed to me, that it would otherwise fit well within the listed criteria, as the only time Minecraft crashes are generally with unexpected behaviors of mods or data packs.
Also, I didn't think minecraft need to crash the way it does to prevent errors. (I thought it crashed that way because it couldn't generate events properly)
Sorry, if I was wrong about what I wrote though.

**Comment by alcatrazEscapee** [comment]
In short, I have no interest in fixing this, and seeing as chocolate's primary bug fix has been, after much trying, gotten fixed in Forge, I don't have the time or motivation to try and remake this mod into something else.
