### ISSUE TITLE
Future request: Fixing mob and block hitboxes

### ISSUE THREAD

**Issue by BunCat09** [alcatrazEscapee/Chocolate#5]
I know that hitboxes of some mobs and blocks really frustrate people. For example hoglins and scaffolding. Maybe oak doors can have those holes get carved too or something. This kind of future could be helpful and make things a bit easier when hitting mobs like hoglins.

**Comment by alcatrazEscapee** [comment]
No, for a couple reasons.

- This isn't a vanilla bug. It's a matter of preference and/or opinion.
- It's a vanilla feature change. For a mod like Chocolate who's intention is to keep vanilla parity while fixing obvious  issues, this is just out of place.
- It's completely unrelated to world generation and/or custom worlds (the focus of this mod).
